Repository godaddy-wordpress/wc-plugin-framework, pull requests merged in 2020-05, with the labels that each got.

#491 Print JS initialization errors to console
  woocommerce/Handlers/Script_Handler.php
Labels: payment-gateway

#494 Fix JS conflict between framework versions
  woocommerce/changelog.txt
  woocommerce/payment-gateway/apple-pay/class-sv-wc-payment-gateway-apple-pay-frontend.php
  woocommerce/payment-gateway/class-sv-wc-payment-gateway-my-payment-methods.php
  woocommerce/payment-gateway/class-sv-wc-payment-gateway-plugin.php
  woocommerce/payment-gateway/class-sv-wc-payment-gateway.php
Labels: bug, payment-gateway

#493 Release: 5.7.1
  woocommerce/changelog.txt
Labels: payment-gateway, release

#495 Fix gateway payment form i18n strings
  woocommerce/payment-gateway/class-sv-wc-payment-gateway.php
Labels: bug
